[package]
name = "garbuild"
version = "0.1.0"
authors = ["ggoraa <ggoraa1029@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
switch_statement = "1.0.0"
minidom = "0.13.0"
colored = "2.0.0"
