name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macOS:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version for macOS
        run: cargo build --release
      - name: Install Windows target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Install MinGW
        run: brew install mingw-w64
#      - name: Install Linux target
#        run: rustup target add x86_64-unknown-linux-musl
      - name: Release version for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu
#      - name: Release version for Linux
#        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: target/release/kumitateru
      - name: Automatic upload to latest alpha
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: |
            target/release/kumitateru
            target/x86_64-pc-windows-gnu/release/kumitateru.exe
#            target/x86_64-unknown-linux-musl/release/kumitateru

  build-Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: target/release/kumitateru

  build-Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: target/release/kumitateru