name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macOS:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: target/release/kumitateru

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: target/release/kumitateru

  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: target/release/kumitateru