name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macOS:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: target/release/kumitateru
      - name: Automatic upload to latest alpha
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-macos"
          prerelease: true
          title: "macOS Latest Development Build"
          files: |
            target/release/kumitateru

  build-Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: target/release/kumitateru
      - name: Automatic upload to latest alpha
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.CD_TOKEN }}"
          automatic_release_tag: "latest-win"
          prerelease: true
          title: "Windows Latest Development Build"
          files: |
            target/release/kumitateru.exe

  build-Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Also build a release version
        run: cargo build --release --verbose

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: target/release/kumitateru
      - name: Automatic upload to latest alpha
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.CD_TOKEN }}"
          automatic_release_tag: "latest-linux"
          prerelease: true
          title: "Linux Latest Development Build"
          files: |
            target/release/kumitateru